const {test}=require('node:test');
const assert=require('node:assert/strict');
const {fixture,settle,deferred}=require('./helpers/runtime.cjs');
const {buildSync}=require('esbuild');
const code=buildSync({entryPoints:['src/lib/jam.ts'],bundle:true,write:false,format:'iife',globalName:'Jam'}).outputFiles[0].text;
function setup(){const f=fixture('<div id="panel"><div class="crp-tab-pane" data-pane="friends"></div><div class="crp-tab-pane" data-pane="devices"></div></div>');f.j=f.w.eval(code+';Jam;');f.mount=()=>f.j.setupJam(f.w.document.querySelector('#panel'));f.button=t=>Array.from(f.w.document.querySelectorAll('button')).find(b=>b.textContent===t);return f;}
test('existing Jam renders participants inline and Devices expands Friends without a native handoff',()=>{const f=setup();try{let created=0,tab;f.w.Spicetify.Platform.SocialConnectAPI={getCurrentSession:()=>({isSessionOwner:true,sessionOwnerId:'a',sessionMembers:[{id:'a',displayName:'Host'},{id:'b',displayName:'<Guest>'}]}),createSession:async()=>{created++;}};f.w.document.addEventListener('crp-switch-tab',e=>tab=e.detail);f.mount();assert.equal(f.w.document.querySelectorAll('.aurora-jam').length,1);assert.equal(f.w.document.querySelectorAll('.aurora-jam-members li').length,2);assert.match(f.w.document.querySelector('ul').textContent,/<Guest>/);f.w.document.querySelector('.aurora-jam-heading').click();assert.equal(f.w.document.querySelector('.aurora-jam-content').hidden,true);f.button('Jam with friends').click();assert.equal(tab,'friends');assert.equal(f.w.document.querySelector('.aurora-jam-content').hidden,false);assert.equal(created,0);assert.equal(f.w.document.body.classList.contains('aurora-native-panel'),false);}finally{f.dom.window.close()}});
test('initial session fetch blocks starting an already active Jam',async()=>{const f=setup();try{const d=deferred();let session=null,created=0;f.w.Spicetify.Platform.SocialConnectAPI={getCurrentSession:()=>session,fetchCurrentSession:()=>d.promise,createSession:async()=>created++};f.mount();assert.equal(f.button('Start a Jam').disabled,true);f.button('Start a Jam').click();session={sessionId:'existing',sessionMembers:[]};d.resolve(session);await settle();assert.equal(created,0);assert.equal(f.button('Start a Jam'),undefined);}finally{f.dom.window.close()}});
test('failed start remains retryable and a concurrent remote session prevents creation',async()=>{const f=setup();try{let session=null,created=0;f.w.Spicetify.Platform.SocialConnectAPI={getCurrentSession:()=>session,getEnabled:()=> 'ENABLED',createSession:async()=>{created++;return null;}};f.mount();f.button('Start a Jam').click();await settle();assert.match(f.w.document.querySelector('[role="status"]').textContent,/Couldn’t/);assert.equal(f.button('Start a Jam').disabled,false);f.w.Spicetify.Platform.SocialConnectAPI.fetchCurrentSession=async()=>{session={sessionId:'remote',sessionMembers:[]}};f.button('Start a Jam').click();await settle();assert.equal(created,1);}finally{f.dom.window.close()}});
test('host end requires inline confirmation; guest gets Leave and failed actions stay visible',async()=>{const f=setup();try{let ended=0;const session={sessionId:'s',isSessionOwner:true,sessionMembers:[]};f.w.Spicetify.Platform.SocialConnectAPI={getCurrentSession:()=>session,deleteSession:async()=>{ended++;return false;},leaveSession:async()=>true};f.mount();f.button('End Jam').click();assert.equal(ended,0);f.button('Cancel').click();assert.equal(ended,0);f.button('End Jam').click();f.button('Confirm').click();await settle();assert.equal(ended,1);assert.match(f.w.document.querySelector('[role="status"]').textContent,/Couldn’t/);session.isSessionOwner=false;f.intervals.find(i=>i.delay===2500).fn();assert.ok(f.button('Leave Jam'));assert.equal(f.button('End Jam'),undefined);}finally{f.dom.window.close()}});
test('invite link copies only on click and clipboard failure is reported',async()=>{const f=setup();try{let copied=[];f.w.Spicetify.Platform.SocialConnectAPI={getCurrentSession:()=>({sessionId:'s',sessionMembers:[]}),getJamJoinInfo:()=>({joinSessionShortLink:{shareableUrl:'https://spotify.link/test'}})};Object.defineProperty(f.w.navigator,'clipboard',{value:{writeText:async x=>copied.push(x)}});f.mount();assert.equal(copied.length,0);f.button('Copy invite link').click();await settle();assert.deepEqual(copied,['https://spotify.link/test']);assert.match(f.w.document.querySelector('[role="status"]').textContent,/copied/);f.w.navigator.clipboard.writeText=async()=>{throw Error()};f.button('Copy invite link').click();await settle();assert.match(f.w.document.querySelector('[role="status"]').textContent,/Couldn’t/);}finally{f.dom.window.close()}});

test('QR is visible by default, enlarges on click, preserves focus while polling, and clears on session end',()=>{const f=setup();try{
 let session={sessionId:'s',sessionMembers:[]},reads=0;
 f.w.Spicetify.Platform.SocialConnectAPI={getCurrentSession:()=>session,getJamJoinInfo:()=>{reads++;return {joinSessionShortLink:{shareableUrl:'https://spotify.link/share'},joinSessionShortLinkQR:{shareableUrl:'https://spotify.link/qr'}}}};
 f.mount();const qr=f.w.document.querySelector('.aurora-jam-qr'),button=qr.querySelector('button');assert.equal(qr.hidden,false);assert.equal(reads,1);assert.equal(f.button('QR code'),undefined);
 assert.equal(button.getAttribute('aria-expanded'),'false');button.focus();button.click();assert.equal(button.getAttribute('aria-expanded'),'true');assert.ok(qr.classList.contains('is-expanded'));assert.ok(f.button('Copy invite link'));
 const svg=qr.querySelector('svg');f.intervals.find(i=>i.delay===2500).fn();assert.equal(qr.querySelector('svg'),svg,'unchanged QR is not regenerated while polling');assert.equal(f.w.document.activeElement,button);
 button.dispatchEvent(new f.w.KeyboardEvent('keydown',{key:'Escape',bubbles:true}));assert.equal(button.getAttribute('aria-expanded'),'false');
 button.click();button.click();assert.equal(button.getAttribute('aria-expanded'),'false');
 button.click();session={sessionId:'new',sessionMembers:[]};f.intervals.find(i=>i.delay===2500).fn();assert.equal(qr.querySelector('button').getAttribute('aria-expanded'),'false');
 session=null;f.intervals.find(i=>i.delay===2500).fn();assert.equal(qr.hidden,true);assert.equal(qr.querySelector('svg'),null);
 }finally{f.dom.window.close()}});
test('unavailable QR automatically retries and clears its error when the invite becomes available',()=>{const f=setup();try{
 let info=null;
 f.w.Spicetify.Platform.SocialConnectAPI={getCurrentSession:()=>({sessionId:'s',sessionMembers:[]}),getJamJoinInfo:()=>info};f.mount();assert.match(f.w.document.querySelector('[role="status"]').textContent,/QR isn’t ready/);assert.equal(f.w.document.querySelector('.aurora-jam-qr').hidden,true);
 info={joinSessionShortLink:{shareableUrl:'https://spotify.link/share'}};f.intervals.find(i=>i.delay===2500).fn();assert.equal(f.w.document.querySelector('.aurora-jam-qr').hidden,false);assert.doesNotMatch(f.w.document.querySelector('[role="status"]').textContent,/QR isn’t ready/);
 }finally{f.dom.window.close()}});
